services:
  - type: web
    name: Salvamento_com_cordas26
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server_api.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://db_salvamento_com_cordas_user:nZvQsGoE6ED6ne026zkML02fjEbtlKWo@dpg-d9mc56ijobas73ao7fk0-a.oregon-postgres.render.com/db_salvamento_com_cordas
