services:
  - type: web
    name: salvamento-com-cordas26
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server_api.py
    envVars:
      - key: DB_PATH
        value: /data/salvamento_2gb.db
      - key: PERSISTENT_DIR
        value: /data
      - key: UPLOADS_DIR
        value: /data/uploads
    disk:
      name: salvamento-cordas-data
      mountPath: /data
      sizeGB: 1
